"""
----------Generated by template----------

DAG with usage examples for MinIO.

"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.utils.trigger_rule import TriggerRule
from airflow.operators.python import PythonOperator

from src import minio_process as minio_process

default_args = {
    'owner': 'data-engineer-project-template',
    'depends_on_past': False,
    'start_date': datetime(2025, 5, 18),
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
    'tags': ['minio', 'buckets']
}

with DAG(
    dag_id='minio_access_example',
    default_args=default_args,
    schedule_interval=None,
    catchup=False,
    doc_md=__doc__,
    description='Examples for MinIO'
) as dag:

    list_minio_buckets = PythonOperator(
        task_id='list_minio_buckets',
        python_callable=minio_process.list_minio_buckets,
        provide_context=True,
    )

    upload_bucket_content = PythonOperator(
        task_id='upload_bucket_content',
        python_callable=minio_process.upload_bucket_content,
        provide_context=True,
    )

    list_bucket_content = PythonOperator(
        task_id='list_bucket_content',
        python_callable=minio_process.list_bucket_content,
        provide_context=True,
    )

    get_bucket_content = PythonOperator(
        task_id='get_bucket_content',
        python_callable=minio_process.get_bucket_content,
        provide_context=True,
    )


    list_minio_buckets >> upload_bucket_content >> list_bucket_content >> get_bucket_content

